<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Comfortaa.ttf" />
    <None Remove="Resources\Fonts\Fredoka.ttf" />
    <None Remove="Resources\Fonts\Lexend.ttf" />
    <None Remove="Resources\Fonts\Manrope.ttf" />
    <None Remove="Resources\Fonts\Montserrat.ttf" />
    <None Remove="Resources\Fonts\Outfit.ttf" />
    <None Remove="Resources\Fonts\Quicksand.ttf" />
    <None Remove="Resources\Shaders\Mandelbrot.ps" />
    <None Remove="Resources\Shaders\Noise.ps" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Comfortaa.ttf" />
    <Resource Include="Resources\Fonts\Fredoka.ttf" />
    <Resource Include="Resources\Fonts\Lexend.ttf" />
    <Resource Include="Resources\Fonts\Manrope.ttf" />
    <Resource Include="Resources\Fonts\Montserrat.ttf" />
    <Resource Include="Resources\Fonts\Outfit.ttf" />
    <Resource Include="Resources\Fonts\Quicksand.ttf" />
    <Resource Include="Resources\Shaders\Mandelbrot.ps" />
    <Resource Include="Resources\Shaders\Noise.ps" />
  </ItemGroup>

</Project>
